---
project:
  title: "Aleksander Bang-Larsen - CV"
  preview:
    browser: false
    port: 4200

author: "Aleksander Bang-Larsen"

format:
  html:
    toc: true
    number_sections: true
    theme:
      light: [flatly, styles.css]
      dark: [darkly, styles.css]
    highlight: github
