---
project:
  title: "Aleksander Bang-Larsen - CV"
  preview:
    browser: false
    port: 4200

author:
  - name: "Aleksander Bang-Larsen"
    email: "cv@aleksanderbl.dk"

lang: "da"
language:
  title-block-author-single: "Navn"
  title-block-modified: "Senest ændret"

format:
  html:
    toc: true
    number_sections: true
    theme:
      light: [flatly, styles.css]
      dark: [darkly, styles.css]
    highlight: github
