---
project:
  title: "Aleksander Bang-Larsen - CV"
  preview:
    browser: false
    port: 4200

author: "Aleksander Bang-Larsen"

format:
  html:
    toc: true
    number_sections: true
    theme: cosmo
    css: styles.css
    highlight: github



#   type: website
#   output-dir: ../cv/_site

# website:
#   title: "Website"
#   navbar:
#     left:
#       - href: index.qmd
#         text: Home
#       - about.qmd

# format:
#   html:
#     theme: cosmo
#     css: styles.css
#     toc: true
