---
name: Build and publish container

on:
  # cron job to trigger the build on any push to main
  push:
    branches:
      - 'main'
    paths:
      - 'Dockerfile
      - 'quarto/**'
      - '.github/workflows/auto-build-container.yml'
  # schedule:
  # # cron job to trigger the build daily
  # # at 3am on Friday
  #   - cron:  '0 3 * * 5'

permissions:
  contents: write

jobs:
  build_container:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Get todays date
      id: date
      run: echo date=$(date +%Y-%m-%d) >> $GITHUB_OUTPUT

    - name: Get branch name
      id: branch
      run: echo branch=$(echo ${{ github.ref }} | sed 's/refs\/heads\///') >> $GITHUB_OUTPUT

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: "{{defaultContext}}"
        platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
        push: true
        tags: aleksanderbl/cv:latest,aleksanderbl/cv:${{ steps.date.outputs.date }}

    - name: Create release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.date.outputs.date }}
        name: "${{ steps.date.outputs.date }}"
        body: |
          CV opdateret d. ${{ steps.date.outputs.date }}
          Kan hentes med `docker pull aleksanderbl/cv:${{ steps.date.outputs.date }}`
